on:
  push:
    tags:
      - 'v*'

name: Build and Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20' # Adjust to your Go version

      - name: Build executable
        run: |
          make build

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: myip
          path: myip
  
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myip

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: myip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}

